# these two come from the pipeline environment
commit: $OKTETO_GIT_COMMIT
branch: $OKTETO_GIT_BRANCH

# this comes from an okteto secret
cookie_smzdm: $cookie_smzdm
cookie_enshan:	$cookie_enshan
Skey:	$Skey
Smode:	$Smode
