# deployment.yaml
apiVersion: v1
kind: Pod
metadata:
  name: checkinbox
  labels:
    app: checkinbox
spec:
  containers:
  - name: container
    image: docker.io/mengshouer/checkinbox:dev
    command: [ "/bin/sh", "-c", "python3 run.py"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: config-app
