# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkinbox
  labels:
    app: checkinbox
spec:
  selector:
    matchLabels:
      app: checkinbox
  template:
    metadata:
      labels:
        app: checkinbox
    spec:
      containers:
      - name: container
        image: docker.io/mengshouer/checkinbox:dev
        command: [ "/bin/sh", "-c"]
        arsg: ["python3 ./Checkin52pj/okteto_Checkin52pj.py && python3 ./V2EX/okteto_v2ex.py && python3 ./Zhiyou/okteto_zhiyou.py"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: config-app
