# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkinbox
  labels:
    app: checkinbox
spec:
  selector:
    matchLabels:
      app: checkinbox
  template:
    metadata:
      labels:
        app: checkinbox
    spec:
      containers:
      - name: container
        image: docker.io/mengshouer/checkinbox:dev
        command: [ "/bin/sh", "-c", "python3 run.py"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: config-app
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: docker.io/mengshouer/checkinbox:dev
    command: ['sh', '-c', 'python3 run.py']
