apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkinbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkinbox
  template:
    metadata:
      labels:
        app: checkinbox
    spec:
      containers:
      - image: docker.io/mengshouer/checkinbox:dev
        name: checkinbox